"""
PricePulse scraper configuration.
Values are loaded from environment variables (set in .env locally,
or GitHub Actions Secrets in production).

Copy this file to .env.local and fill in your credentials:
  SUPABASE_URL=https://xxxx.supabase.co
  SUPABASE_SERVICE_KEY=your-service-role-key
"""

import os
from dotenv import load_dotenv

load_dotenv()

# ── Supabase ────────────────────────────────────────
SUPABASE_URL         = os.getenv('SUPABASE_URL', '')
SUPABASE_SERVICE_KEY = os.getenv('SUPABASE_SERVICE_KEY', '')

if not SUPABASE_URL or not SUPABASE_SERVICE_KEY:
    raise EnvironmentError(
        "Missing SUPABASE_URL or SUPABASE_SERVICE_KEY. "
        "Create a .env file based on .env.example."
    )

# ── Scraper behaviour ───────────────────────────────
REQUEST_TIMEOUT   = 15       # seconds per HTTP request
REQUEST_DELAY     = 4.5      # seconds between requests (be polite)
MAX_RETRIES       = 3        # retry failed requests this many times
MOCK_MODE         = os.getenv('MOCK_MODE', 'false').lower() == 'true'
                             # Set MOCK_MODE=true to skip real HTTP calls during dev

# ── Products to track ───────────────────────────────
# Each entry: product_id (matches Supabase), search term per store
TRACKED_ITEMS = [
    {
        'id': 'coca-cola-125l',
        'woolworths_term': 'coca-cola classic',
        'coles_term':      'coca-cola classic',
        'amazon_asin':     None,
    },
    {
        'id': 'pepsi-max-125l',
        'woolworths_term': 'pepsi max cola no sugar',
        'coles_term':      'pepsi max cola no sugar',
        'amazon_asin':     None,
    },
    {
        'id': 'sprite-125l',
        'woolworths_term': 'sprite lemonade',
        'coles_term':      'sprite lemonade',
        'amazon_asin':     None,
    },
    {
        'id': 'solo-125l',
        'woolworths_term': 'solo original lemon',
        'coles_term':      'solo original lemon',
        'amazon_asin':     None,
    },
    {
        'id': 'mt-franklin-600ml',
        'woolworths_term': 'mount franklin sparkling',
        'coles_term':      'mount franklin sparkling',
        'amazon_asin':     None,
    },
    {
        'id': 'red-bull-4pk',
        'woolworths_term': 'red bull energy drink',
        'coles_term':      'red bull energy drink',
        'amazon_asin':     None,
    },
    {
        'id': 'v-energy-drink-500ml',
        'woolworths_term': 'v green energy can',
        'coles_term':      'v green energy can',
        'amazon_asin':     None,
    },
    {
        'id': 'lipton-ice-tea-peach-15l',
        'woolworths_term': 'lipton ice tea peach',
        'coles_term':      'lipton ice tea peach',
        'amazon_asin':     None,
    },
    {
        'id': 'fanta-orange-125l',
        'woolworths_term': 'fanta orange',
        'coles_term':      'fanta orange',
        'amazon_asin':     None,
    },
    {
        'id': 'schweppes-lemonade-11l',
        'woolworths_term': 'schweppes lemonade',
        'coles_term':      'schweppes lemonade',
        'amazon_asin':     None,
    },
    {
        'id': 'kirks-pasito-10pk',
        'woolworths_term': 'kirks pasito cans',
        'coles_term':      'kirks pasito cans',
        'amazon_asin':     None,
    },
    {
        'id': 'gatorade-blue-bolt-1l',
        'woolworths_term': 'gatorade blue bolt',
        'coles_term':      'gatorade blue bolt',
        'amazon_asin':     None,
    },
    {
        'id': 'powerade-berry-ice-600ml',
        'woolworths_term': 'powerade berry ice',
        'coles_term':      'powerade berry ice',
        'amazon_asin':     None,
    },
    {
        'id': 'bundaberg-ginger-beer-4pk',
        'woolworths_term': 'bundaberg ginger beer',
        'coles_term':      'bundaberg ginger beer',
        'amazon_asin':     None,
    },
    {
        'id': 'coke-zero-30pk',
        'woolworths_term': 'coca-cola zero sugar cans',
        'coles_term':      'coca-cola zero sugar cans',
        'amazon_asin':     None,
    },
    {
        'id': 'skittles-original-160g',
        'woolworths_term': 'skittles original fruit',
        'coles_term':      'skittles original fruit',
        'amazon_asin':     None,
    },
    {
        'id': 'allens-snakes-220g',
        'woolworths_term': 'allens snakes alive',
        'coles_term':      'allens snakes alive',
        'amazon_asin':     None,
    },
    {
        'id': 'mentos-fruit-roll',
        'woolworths_term': 'mentos fruit roll',
        'coles_term':      'mentos fruit roll',
        'amazon_asin':     None,
    },
    {
        'id': 'allens-party-mix-190g',
        'woolworths_term': 'allens party mix',
        'coles_term':      'allens party mix',
        'amazon_asin':     None,
    },
    {
        'id': 'starburst-snakes-170g',
        'woolworths_term': 'starburst sour snakes',
        'coles_term':      'starburst sour snakes',
        'amazon_asin':     None,
    },
    {
        'id': 'haribo-goldbears-150g',
        'woolworths_term': 'haribo goldbears',
        'coles_term':      'haribo goldbears',
        'amazon_asin':     None,
    },
    {
        'id': 'chupa-chups-10pk',
        'woolworths_term': 'chupa chups lollipops',
        'coles_term':      'chupa chups lollipops',
        'amazon_asin':     None,
    },
    {
        'id': 'natural-confectionery-snakes-260g',
        'woolworths_term': 'tncc snakes',
        'coles_term':      'tncc snakes',
        'amazon_asin':     None,
    },
    {
        'id': 'pascall-marshmallows-280g',
        'woolworths_term': 'pascall vanilla marshmallows',
        'coles_term':      'pascall vanilla marshmallows',
        'amazon_asin':     None,
    },
    {
        'id': 'red-skins-allen-220g',
        'woolworths_term': 'allens red ripperz',
        'coles_term':      'allens red ripperz',
        'amazon_asin':     None,
    },
    {
        'id': 'werthers-original-140g',
        'woolworths_term': 'werthers original butter candies',
        'coles_term':      'werthers original butter candies',
        'amazon_asin':     None,
    },
    {
        'id': 'eclipse-mints-peppermint-40g',
        'woolworths_term': 'eclipse mints peppermint',
        'coles_term':      'eclipse mints peppermint',
        'amazon_asin':     None,
    },
    {
        'id': 'mentos-mint-rolls-4pk',
        'woolworths_term': 'mentos mint rolls',
        'coles_term':      'mentos mint rolls',
        'amazon_asin':     None,
    },
    {
        'id': 'tictac-freshmint-24g',
        'woolworths_term': 'tic tac fresh mint',
        'coles_term':      'tic tac fresh mint',
        'amazon_asin':     None,
    },
    {
        'id': 'sour-patch-kids-190g',
        'woolworths_term': 'sour patch kids',
        'coles_term':      'sour patch kids',
        'amazon_asin':     None,
    },
    {
        'id': 'cadbury-dairy-milk-180g',
        'woolworths_term': 'cadbury dairy milk block',
        'coles_term':      'cadbury dairy milk block',
        'amazon_asin':     None,
    },
    {
        'id': 'cadbury-favourites-500g',
        'woolworths_term': 'cadbury favourites box',
        'coles_term':      'cadbury favourites box',
        'amazon_asin':     None,
    },
    {
        'id': 'kitkat-chunky-4pk',
        'woolworths_term': 'kit kat chunky pack',
        'coles_term':      'kit kat chunky pack',
        'amazon_asin':     None,
    },
    {
        'id': 'lindt-excellence-85g',
        'woolworths_term': 'lindt excellence 70% dark',
        'coles_term':      'lindt excellence 70% dark',
        'amazon_asin':     None,
    },
    {
        'id': 'snickers-4pk',
        'woolworths_term': 'snickers multipack',
        'coles_term':      'snickers multipack',
        'amazon_asin':     None,
    },
    {
        'id': 'arnotts-tim-tam-200g',
        'woolworths_term': 'arnotts tim tam original',
        'coles_term':      'arnotts tim tam original',
        'amazon_asin':     None,
    },
    {
        'id': 'maltesers-400g',
        'woolworths_term': 'maltesers chocolate bucket',
        'coles_term':      'maltesers chocolate bucket',
        'amazon_asin':     None,
    },
    {
        'id': 'mms-milk-chocolate-180g',
        'woolworths_term': 'mms milk chocolate bag',
        'coles_term':      'mms milk chocolate bag',
        'amazon_asin':     None,
    },
    {
        'id': 'pods-snickers-160g',
        'woolworths_term': 'pods snickers chocolate',
        'coles_term':      'pods snickers chocolate',
        'amazon_asin':     None,
    },
    {
        'id': 'mars-bar-53g',
        'woolworths_term': 'mars bar single',
        'coles_term':      'mars bar single',
        'amazon_asin':     None,
    },
    {
        'id': 'cherry-ripe-double-dipped-block',
        'woolworths_term': 'cadbury cherry ripe block',
        'coles_term':      'cadbury cherry ripe block',
        'amazon_asin':     None,
    },
    {
        'id': 'toblerone-milk-360g',
        'woolworths_term': 'toblerone milk chocolate',
        'coles_term':      'toblerone milk chocolate',
        'amazon_asin':     None,
    },
    {
        'id': 'ferrero-rocher-16pk',
        'woolworths_term': 'ferrero rocher gift box',
        'coles_term':      'ferrero rocher gift box',
        'amazon_asin':     None,
    },
    {
        'id': 'twirl-cadbury-5pk',
        'woolworths_term': 'cadbury twirl multipack',
        'coles_term':      'cadbury twirl multipack',
        'amazon_asin':     None,
    },
    {
        'id': 'picnic-bar-4pk',
        'woolworths_term': 'cadbury picnic multipack',
        'coles_term':      'cadbury picnic multipack',
        'amazon_asin':     None,
    },
    {
        'id': 'pringles-original-134g',
        'woolworths_term': 'pringles original',
        'coles_term':      'pringles original',
        'amazon_asin':     None,
    },
    {
        'id': 'smiths-crinkle-150g',
        'woolworths_term': 'smiths crinkle cut potato',
        'coles_term':      'smiths crinkle cut potato',
        'amazon_asin':     None,
    },
    {
        'id': 'kettle-sea-salt-150g',
        'woolworths_term': 'kettle sea salt chips',
        'coles_term':      'kettle sea salt chips',
        'amazon_asin':     None,
    },
    {
        'id': 'doritos-cheese-170g',
        'woolworths_term': 'doritos cheese supreme',
        'coles_term':      'doritos cheese supreme',
        'amazon_asin':     None,
    },
    {
        'id': 'thins-original-175g',
        'woolworths_term': 'thins chips light  tangy',
        'coles_term':      'thins chips light  tangy',
        'amazon_asin':     None,
    },
    {
        'id': 'twisties-cheese-90g',
        'woolworths_term': 'twisties cheese',
        'coles_term':      'twisties cheese',
        'amazon_asin':     None,
    },
    {
        'id': 'red-rock-deli-sea-salt-165g',
        'woolworths_term': 'red rock deli sea salt',
        'coles_term':      'red rock deli sea salt',
        'amazon_asin':     None,
    },
    {
        'id': 'cheezels-cheese-box-125g',
        'woolworths_term': 'cheezels cheese snacks box',
        'coles_term':      'cheezels cheese snacks box',
        'amazon_asin':     None,
    },
    {
        'id': 'shapes-bbq-arnotts-175g',
        'woolworths_term': 'arnotts shapes bbq',
        'coles_term':      'arnotts shapes bbq',
        'amazon_asin':     None,
    },
    {
        'id': 'grainwaves-sour-cream-170g',
        'woolworths_term': 'grainwaves sour cream  chives',
        'coles_term':      'grainwaves sour cream  chives',
        'amazon_asin':     None,
    },
    {
        'id': 'smiths-thinly-cut-175g',
        'woolworths_term': 'smiths thinly cut sour cream',
        'coles_term':      'smiths thinly cut sour cream',
        'amazon_asin':     None,
    },
    {
        'id': 'cc-tasty-cheese-175g',
        'woolworths_term': 'ccs tasty cheese corn chips',
        'coles_term':      'ccs tasty cheese corn chips',
        'amazon_asin':     None,
    },
    {
        'id': 'red-rock-honey-soy-165g',
        'woolworths_term': 'red rock deli honey soy chicken',
        'coles_term':      'red rock deli honey soy chicken',
        'amazon_asin':     None,
    },
    {
        'id': 'vege-chips-natural-100g',
        'woolworths_term': 'vege chips natural flavor',
        'coles_term':      'vege chips natural flavor',
        'amazon_asin':     None,
    },
    {
        'id': 'infuzions-vege-straws-110g',
        'woolworths_term': 'infuzions veggie straws sour cream',
        'coles_term':      'infuzions veggie straws sour cream',
        'amazon_asin':     None,
    },
    {
        'id': 'magnum-classic-4pk',
        'woolworths_term': 'magnum classic chocolate sticks',
        'coles_term':      'magnum classic chocolate sticks',
        'amazon_asin':     None,
    },
    {
        'id': 'ben-jerrys-458ml',
        'woolworths_term': 'ben  jerry half baked tub',
        'coles_term':      'ben  jerry half baked tub',
        'amazon_asin':     None,
    },
    {
        'id': 'streets-blue-ribbon-2l',
        'woolworths_term': 'streets blue ribbon vanilla',
        'coles_term':      'streets blue ribbon vanilla',
        'amazon_asin':     None,
    },
    {
        'id': 'connoisseur-vanilla-1l',
        'woolworths_term': 'connoisseur classic vanilla',
        'coles_term':      'connoisseur classic vanilla',
        'amazon_asin':     None,
    },
    {
        'id': 'bull-creamy-classics-2l',
        'woolworths_term': 'bulla creamy classics vanilla',
        'coles_term':      'bulla creamy classics vanilla',
        'amazon_asin':     None,
    },
    {
        'id': 'peters-original-vanilla-4l',
        'woolworths_term': 'peters original vanilla tub',
        'coles_term':      'peters original vanilla tub',
        'amazon_asin':     None,
    },
    {
        'id': 'drumstick-vanilla-4pk',
        'woolworths_term': 'peters drumstick vanilla cone',
        'coles_term':      'peters drumstick vanilla cone',
        'amazon_asin':     None,
    },
    {
        'id': 'maxibon-original-4pk',
        'woolworths_term': 'peters maxibon vanilla sticks',
        'coles_term':      'peters maxibon vanilla sticks',
        'amazon_asin':     None,
    },
    {
        'id': 'cornetto-classic-4pk',
        'woolworths_term': 'streets cornetto chocolate cone',
        'coles_term':      'streets cornetto chocolate cone',
        'amazon_asin':     None,
    },
    {
        'id': 'weis-mango-bar-4pk',
        'woolworths_term': 'weis mango ice cream bars',
        'coles_term':      'weis mango ice cream bars',
        'amazon_asin':     None,
    },
    {
        'id': 'golden-gaytime-4pk',
        'woolworths_term': 'streets golden gaytime sticks',
        'coles_term':      'streets golden gaytime sticks',
        'amazon_asin':     None,
    },
    {
        'id': 'paddle-pop-rainbow-8pk',
        'woolworths_term': 'streets paddle pop rainbow',
        'coles_term':      'streets paddle pop rainbow',
        'amazon_asin':     None,
    },
    {
        'id': 'hagan-dazs-macadamia-460ml',
        'woolworths_term': 'haagen-dazs macadamia nut',
        'coles_term':      'haagen-dazs macadamia nut',
        'amazon_asin':     None,
    },
    {
        'id': 'streets-splices-pine-lime-8pk',
        'woolworths_term': 'streets splice pine lime',
        'coles_term':      'streets splice pine lime',
        'amazon_asin':     None,
    },
    {
        'id': 'monaco-bar-ice-cream-4pk',
        'woolworths_term': 'peters monaco bar ice cream sandwich',
        'coles_term':      'peters monaco bar ice cream sandwich',
        'amazon_asin':     None,
    },
    {
        'id': 'woolworths-milk-2l',
        'woolworths_term': 'ww full cream milk',
        'coles_term':      'ww full cream milk',
        'amazon_asin':     None,
    },
    {
        'id': 'tip-top-bread-700g',
        'woolworths_term': 'tip top bread toast slices',
        'coles_term':      'tip top bread toast slices',
        'amazon_asin':     None,
    },
    {
        'id': 'western-star-butter-500g',
        'woolworths_term': 'western star butter salted block',
        'coles_term':      'western star butter salted block',
        'amazon_asin':     None,
    },
    {
        'id': 'nescafe-blend-43-150g',
        'woolworths_term': 'nescafe blend 43 instant coffee',
        'coles_term':      'nescafe blend 43 instant coffee',
        'amazon_asin':     None,
    },
    {
        'id': 'weetbix-1.2kg',
        'woolworths_term': 'sanitarium weet-bix',
        'coles_term':      'sanitarium weet-bix',
        'amazon_asin':     None,
    },
    {
        'id': 'quilton-toilet-paper-18pk',
        'woolworths_term': 'quilton toilet paper 3ply',
        'coles_term':      'quilton toilet paper 3ply',
        'amazon_asin':     None,
    },
    {
        'id': 'dairy-farmers-milk-3l',
        'woolworths_term': 'dairy farmers full cream milk',
        'coles_term':      'dairy farmers full cream milk',
        'amazon_asin':     None,
    },
    {
        'id': 'wonder-white-bread-700g',
        'woolworths_term': 'wonder white sliced bread sandwich',
        'coles_term':      'wonder white sliced bread sandwich',
        'amazon_asin':     None,
    },
    {
        'id': 'devondale-butter-500g',
        'woolworths_term': 'devondale salted butter block',
        'coles_term':      'devondale salted butter block',
        'amazon_asin':     None,
    },
    {
        'id': 'dilmah-tea-bags-100pk',
        'woolworths_term': 'dilmah premium tea bags',
        'coles_term':      'dilmah premium tea bags',
        'amazon_asin':     None,
    },
    {
        'id': 'lipton-tea-bags-100pk',
        'woolworths_term': 'lipton quality black tea bags',
        'coles_term':      'lipton quality black tea bags',
        'amazon_asin':     None,
    },
    {
        'id': 'moccona-medium-roast-200g',
        'woolworths_term': 'moccona classic medium coffee jar',
        'coles_term':      'moccona classic medium coffee jar',
        'amazon_asin':     None,
    },
    {
        'id': 'uncle-tobys-rolled-oats-1kg',
        'woolworths_term': 'uncle tobys rolled oats bag',
        'coles_term':      'uncle tobys rolled oats bag',
        'amazon_asin':     None,
    },
    {
        'id': 'sorbent-toilet-paper-24pk',
        'woolworths_term': 'sorbent toilet paper silky white',
        'coles_term':      'sorbent toilet paper silky white',
        'amazon_asin':     None,
    },
    {
        'id': 'coles-milk-2l',
        'woolworths_term': 'coles full cream milk',
        'coles_term':      'coles full cream milk',
        'amazon_asin':     None,
    },
    {
        'id': 'san-remo-pasta-500g',
        'woolworths_term': 'san remo spaghetti pasta',
        'coles_term':      'san remo spaghetti pasta',
        'amazon_asin':     None,
    },
    {
        'id': 'sunrice-jasmine-rice-5kg',
        'woolworths_term': 'sunrice jasmine rice bag',
        'coles_term':      'sunrice jasmine rice bag',
        'amazon_asin':     None,
    },
    {
        'id': 'cobram-estate-olive-oil-750ml',
        'woolworths_term': 'cobram estate ev olive oil',
        'coles_term':      'cobram estate ev olive oil',
        'amazon_asin':     None,
    },
    {
        'id': 'john-west-tuna-95g',
        'woolworths_term': 'john west tuna tempters olive oil',
        'coles_term':      'john west tuna tempters olive oil',
        'amazon_asin':     None,
    },
    {
        'id': 'leggos-tomato-paste-500g',
        'woolworths_term': 'leggos tomato paste tub',
        'coles_term':      'leggos tomato paste tub',
        'amazon_asin':     None,
    },
    {
        'id': 'bega-peanut-butter-375g',
        'woolworths_term': 'bega peanut butter crunchy',
        'coles_term':      'bega peanut butter crunchy',
        'amazon_asin':     None,
    },
    {
        'id': 'vegemite-220g',
        'woolworths_term': 'vegemite yeast extract jar',
        'coles_term':      'vegemite yeast extract jar',
        'amazon_asin':     None,
    },
    {
        'id': 'spaghetti-pasta-san-remo-fettuccine',
        'woolworths_term': 'san remo fettuccine pasta no 34',
        'coles_term':      'san remo fettuccine pasta no 34',
        'amazon_asin':     None,
    },
    {
        'id': 'heinz-baked-beans-3pk',
        'woolworths_term': 'heinz baked beans english recipe',
        'coles_term':      'heinz baked beans english recipe',
        'amazon_asin':     None,
    },
    {
        'id': 'campbells-tomato-soup-400g',
        'woolworths_term': 'campbells condensed tomato soup',
        'coles_term':      'campbells condensed tomato soup',
        'amazon_asin':     None,
    },
    {
        'id': 'glen-20-disinfectant-spray-300g',
        'woolworths_term': 'glen 20 disinfectant lavender',
        'coles_term':      'glen 20 disinfectant lavender',
        'amazon_asin':     None,
    },
    {
        'id': 'heinz-tomato-ketchup-500ml',
        'woolworths_term': 'heinz tomato ketchup squeeze',
        'coles_term':      'heinz tomato ketchup squeeze',
        'amazon_asin':     None,
    },
    {
        'id': 'masterfoods-tomato-sauce-500ml',
        'woolworths_term': 'masterfoods tomato sauce squeeze',
        'coles_term':      'masterfoods tomato sauce squeeze',
        'amazon_asin':     None,
    },
    {
        'id': 'spam-luncheon-meat-340g',
        'woolworths_term': 'spam luncheon meat can',
        'coles_term':      'spam luncheon meat can',
        'amazon_asin':     None,
    },
    {
        'id': 'spc-sliced-peaches-410g',
        'woolworths_term': 'spc sliced peaches in juice',
        'coles_term':      'spc sliced peaches in juice',
        'amazon_asin':     None,
    },
    {
        'id': 'cavendish-bananas-1kg',
        'woolworths_term': 'cavendish bananas fresh',
        'coles_term':      'cavendish bananas fresh',
        'amazon_asin':     None,
    },
    {
        'id': 'pink-lady-apples-1kg',
        'woolworths_term': 'pink lady apples pack',
        'coles_term':      'pink lady apples pack',
        'amazon_asin':     None,
    },
    {
        'id': 'carrots-1kg',
        'woolworths_term': 'carrots orange bag',
        'coles_term':      'carrots orange bag',
        'amazon_asin':     None,
    },
    {
        'id': 'avocado-hass-each',
        'woolworths_term': 'hass avocado single',
        'coles_term':      'hass avocado single',
        'amazon_asin':     None,
    },
    {
        'id': 'brown-onions-1kg',
        'woolworths_term': 'brown onions fresh bag',
        'coles_term':      'brown onions fresh bag',
        'amazon_asin':     None,
    },
    {
        'id': 'potatoes-brushed-2kg',
        'woolworths_term': 'brushed potatoes bag',
        'coles_term':      'brushed potatoes bag',
        'amazon_asin':     None,
    },
    {
        'id': 'broccoli-fresh-each',
        'woolworths_term': 'broccoli premium head',
        'coles_term':      'broccoli premium head',
        'amazon_asin':     None,
    },
    {
        'id': 'red-seedless-grapes-500g',
        'woolworths_term': 'red seedless grapes punnet',
        'coles_term':      'red seedless grapes punnet',
        'amazon_asin':     None,
    },
    {
        'id': 'navel-oranges-1kg',
        'woolworths_term': 'navel oranges bag',
        'coles_term':      'navel oranges bag',
        'amazon_asin':     None,
    },
    {
        'id': 'punnet-strawberries-250g',
        'woolworths_term': 'strawberries sweet punnet',
        'coles_term':      'strawberries sweet punnet',
        'amazon_asin':     None,
    },
    {
        'id': 'cherry-tomatoes-250g',
        'woolworths_term': 'cherry tomatoes punnet',
        'coles_term':      'cherry tomatoes punnet',
        'amazon_asin':     None,
    },
    {
        'id': 'baby-spinach-leaves-120g',
        'woolworths_term': 'baby spinach leaves tub',
        'coles_term':      'baby spinach leaves tub',
        'amazon_asin':     None,
    },
    {
        'id': 'iceberg-lettuce-each',
        'woolworths_term': 'iceberg lettuce head',
        'coles_term':      'iceberg lettuce head',
        'amazon_asin':     None,
    },
    {
        'id': 'continental-cucumber-each',
        'woolworths_term': 'continental cucumber fresh',
        'coles_term':      'continental cucumber fresh',
        'amazon_asin':     None,
    },
    {
        'id': 'red-capsicum-each',
        'woolworths_term': 'red capsicum fresh single',
        'coles_term':      'red capsicum fresh single',
        'amazon_asin':     None,
    },
    {
        'id': 'bega-cheese-block-500g',
        'woolworths_term': 'bega tasty cheese block',
        'coles_term':      'bega tasty cheese block',
        'amazon_asin':     None,
    },
    {
        'id': 'yoplait-vanilla-yogurt-1kg',
        'woolworths_term': 'yoplait vanilla yogurt tub',
        'coles_term':      'yoplait vanilla yogurt tub',
        'amazon_asin':     None,
    },
    {
        'id': 'chobani-greek-yogurt-170g',
        'woolworths_term': 'chobani greek yogurt blueberry',
        'coles_term':      'chobani greek yogurt blueberry',
        'amazon_asin':     None,
    },
    {
        'id': 'coon-tasty-cheese-block-500g',
        'woolworths_term': 'cheer tasty cheese block',
        'coles_term':      'cheer tasty cheese block',
        'amazon_asin':     None,
    },
    {
        'id': 'philadelphia-cream-cheese-250g',
        'woolworths_term': 'philadelphia cream cheese spread',
        'coles_term':      'philadelphia cream cheese spread',
        'amazon_asin':     None,
    },
    {
        'id': 'dairy-farmers-sour-cream-300g',
        'woolworths_term': 'dairy farmers sour cream tub',
        'coles_term':      'dairy farmers sour cream tub',
        'amazon_asin':     None,
    },
    {
        'id': 'perfect-italian-mozzarella-250g',
        'woolworths_term': 'perfect italian mozzarella grated',
        'coles_term':      'perfect italian mozzarella grated',
        'amazon_asin':     None,
    },
    {
        'id': 'mainland-tasty-cheese-slices-250g',
        'woolworths_term': 'mainland tasty slices 10pk',
        'coles_term':      'mainland tasty slices 10pk',
        'amazon_asin':     None,
    },
    {
        'id': 'flora-proactiv-margarine-250g',
        'woolworths_term': 'flora proactiv margarine spread',
        'coles_term':      'flora proactiv margarine spread',
        'amazon_asin':     None,
    },
    {
        'id': 'giel-thickened-cream-600ml',
        'woolworths_term': 'bulla thickened cream bottle',
        'coles_term':      'bulla thickened cream bottle',
        'amazon_asin':     None,
    },
    {
        'id': 'danone-activia-yogurt-4pk',
        'woolworths_term': 'danone activia probiotics yogurt',
        'coles_term':      'danone activia probiotics yogurt',
        'amazon_asin':     None,
    },
    {
        'id': 'chobani-yogurt-pouch-140g',
        'woolworths_term': 'chobani greek yogurt pouch strawberry',
        'coles_term':      'chobani greek yogurt pouch strawberry',
        'amazon_asin':     None,
    },
    {
        'id': 'yakult-fermented-milk-5pk',
        'woolworths_term': 'yakult fermented milk drink',
        'coles_term':      'yakult fermented milk drink',
        'amazon_asin':     None,
    },
    {
        'id': 'woolworths-feta-cheese-200g',
        'woolworths_term': 'woolworths danish feta cheese',
        'coles_term':      'woolworths danish feta cheese',
        'amazon_asin':     None,
    },
    {
        'id': 'castello-creamy-blue-cheese-150g',
        'woolworths_term': 'castello double cream blue cheese',
        'coles_term':      'castello double cream blue cheese',
        'amazon_asin':     None,
    },
    {
        'id': 'cold-power-laundry-liquid-2l',
        'woolworths_term': 'cold power laundry liquid sensitive',
        'coles_term':      'cold power laundry liquid sensitive',
        'amazon_asin':     None,
    },
    {
        'id': 'fairy-dishwasher-tablets-44pk',
        'woolworths_term': 'fairy dishwasher tablets plus',
        'coles_term':      'fairy dishwasher tablets plus',
        'amazon_asin':     None,
    },
    {
        'id': 'dettol-liquid-handwash-refill-500ml',
        'woolworths_term': 'dettol handwash liquid refill',
        'coles_term':      'dettol handwash liquid refill',
        'amazon_asin':     None,
    },
    {
        'id': 'finish-dishwasher-rinse-aid-500ml',
        'woolworths_term': 'finish rinse aid jet dry',
        'coles_term':      'finish rinse aid jet dry',
        'amazon_asin':     None,
    },
    {
        'id': 'morning-fresh-dish-liquid-400ml',
        'woolworths_term': 'morning fresh lemon dishwashing',
        'coles_term':      'morning fresh lemon dishwashing',
        'amazon_asin':     None,
    },
    {
        'id': 'harpic-active-fresh-toilet-cleaner-700ml',
        'woolworths_term': 'harpic toilet cleaner gel marine',
        'coles_term':      'harpic toilet cleaner gel marine',
        'amazon_asin':     None,
    },
    {
        'id': 'pine-o-cleen-disinfectant-wipes-120pk',
        'woolworths_term': 'pine o cleen disinfectant wipes lemon',
        'coles_term':      'pine o cleen disinfectant wipes lemon',
        'amazon_asin':     None,
    },
    {
        'id': 'ajax-spray-wipe-glass-cleaner-500ml',
        'woolworths_term': 'ajax spray n wipe glass cleaner',
        'coles_term':      'ajax spray n wipe glass cleaner',
        'amazon_asin':     None,
    },
    {
        'id': 'palmolive-dish-liquid-original-750ml',
        'woolworths_term': 'palmolive ultra dishwashing liquid',
        'coles_term':      'palmolive ultra dishwashing liquid',
        'amazon_asin':     None,
    },
    {
        'id': 'earth-choice-dish-liquid-1l',
        'woolworths_term': 'earth choice lemon dishwashing liquid',
        'coles_term':      'earth choice lemon dishwashing liquid',
        'amazon_asin':     None,
    },
    {
        'id': 'vanish-napisan-oxipromote-3kg',
        'woolworths_term': 'vanish napisan oxi action powder',
        'coles_term':      'vanish napisan oxi action powder',
        'amazon_asin':     None,
    },
    {
        'id': 'dynamo-laundry-liquid-2l',
        'woolworths_term': 'dynamo professional laundry liquid',
        'coles_term':      'dynamo professional laundry liquid',
        'amazon_asin':     None,
    },
    {
        'id': 'comfort-fabric-softener-900ml',
        'woolworths_term': 'comfort fabric conditioner pure',
        'coles_term':      'comfort fabric conditioner pure',
        'amazon_asin':     None,
    },
    {
        'id': 'duck-toilet-fresh-disc-starter',
        'woolworths_term': 'toilet duck fresh discs lime',
        'coles_term':      'toilet duck fresh discs lime',
        'amazon_asin':     None,
    },
    {
        'id': 'chux-superwipes-10pk',
        'woolworths_term': 'chux superwipes roll cloths',
        'coles_term':      'chux superwipes roll cloths',
        'amazon_asin':     None,
    },
    {
        'id': 'wonder-white-bread-sliced-700g',
        'woolworths_term': 'wonder white sliced toast bread',
        'coles_term':      'wonder white sliced toast bread',
        'amazon_asin':     None,
    },
    {
        'id': 'helgas-rye-bread-680g',
        'woolworths_term': 'helgas traditional rye slices',
        'coles_term':      'helgas traditional rye slices',
        'amazon_asin':     None,
    },
    {
        'id': 'abbotts-sourdough-bread-loaf',
        'woolworths_term': 'abbotts bakery sourdough loaf',
        'coles_term':      'abbotts bakery sourdough loaf',
        'amazon_asin':     None,
    },
    {
        'id': 'coles-croissants-3pk',
        'woolworths_term': 'coles bakery croissants',
        'coles_term':      'coles bakery croissants',
        'amazon_asin':     None,
    },
    {
        'id': 'woolworths-muffins-choc-chip-4pk',
        'woolworths_term': 'ww choc chip muffins 4pk',
        'coles_term':      'ww choc chip muffins 4pk',
        'amazon_asin':     None,
    },
    {
        'id': 'helgas-wholemeal-bread-680g',
        'woolworths_term': 'helgas traditional wholemeal loaf',
        'coles_term':      'helgas traditional wholemeal loaf',
        'amazon_asin':     None,
    },
    {
        'id': 'mission-tortillas-large-8pk',
        'woolworths_term': 'mission original tortillas large',
        'coles_term':      'mission original tortillas large',
        'amazon_asin':     None,
    },
    {
        'id': 'tiptop-english-muffins-6pk',
        'woolworths_term': 'tip top english muffins original',
        'coles_term':      'tip top english muffins original',
        'amazon_asin':     None,
    },
    {
        'id': 'woolworths-crumpets-6pk',
        'woolworths_term': 'woolworths crumpets original',
        'coles_term':      'woolworths crumpets original',
        'amazon_asin':     None,
    },
    {
        'id': 'tiptop-raisin-toast-bread-520g',
        'woolworths_term': 'tip top cafe raisin toast bread',
        'coles_term':      'tip top cafe raisin toast bread',
        'amazon_asin':     None,
    },
    {
        'id': 'mission-pita-bread-pocket-5pk',
        'woolworths_term': 'mission white pita bread pocket',
        'coles_term':      'mission white pita bread pocket',
        'amazon_asin':     None,
    },
    {
        'id': 'coles-chocolate-cookies-12pk',
        'woolworths_term': 'coles chocolate chip cookies bakery',
        'coles_term':      'coles chocolate chip cookies bakery',
        'amazon_asin':     None,
    },
    {
        'id': 'kelloggs-nutrigrain-500g',
        'woolworths_term': 'kelloggs nutri-grain cereal',
        'coles_term':      'kelloggs nutri-grain cereal',
        'amazon_asin':     None,
    },
    {
        'id': 'kelloggs-corn-flakes-380g',
        'woolworths_term': 'kelloggs corn flakes box',
        'coles_term':      'kelloggs corn flakes box',
        'amazon_asin':     None,
    },
    {
        'id': 'sanitarium-weetbix-1kg',
        'woolworths_term': 'sanitarium weet-bix cereal box',
        'coles_term':      'sanitarium weet-bix cereal box',
        'amazon_asin':     None,
    },
    {
        'id': 'uncle-tobys-plus-sports-cereal',
        'woolworths_term': 'uncle tobys plus sports protein',
        'coles_term':      'uncle tobys plus sports protein',
        'amazon_asin':     None,
    },
    {
        'id': 'kelloggs-coco-pops-375g',
        'woolworths_term': 'kelloggs coco pops cereal chocolate',
        'coles_term':      'kelloggs coco pops cereal chocolate',
        'amazon_asin':     None,
    },
    {
        'id': 'kelloggs-sultana-bran-420g',
        'woolworths_term': 'kelloggs sultana bran cereal box',
        'coles_term':      'kelloggs sultana bran cereal box',
        'amazon_asin':     None,
    },
    {
        'id': 'uncle-tobys-oat-quick-sachets',
        'woolworths_term': 'uncle tobys quick sachets creamy honey',
        'coles_term':      'uncle tobys quick sachets creamy honey',
        'amazon_asin':     None,
    },
    {
        'id': 'carman-muesli-golden-oat-500g',
        'woolworths_term': 'carmans golden oat crunchy muesli',
        'coles_term':      'carmans golden oat crunchy muesli',
        'amazon_asin':     None,
    },
    {
        'id': 'kelloggs-froot-loops-285g',
        'woolworths_term': 'kelloggs froot loops colored cereal',
        'coles_term':      'kelloggs froot loops colored cereal',
        'amazon_asin':     None,
    },
    {
        'id': 'sanitarium-upandgo-choc-6pk',
        'woolworths_term': 'sanitarium up  go liquid breakfast choc',
        'coles_term':      'sanitarium up  go liquid breakfast choc',
        'amazon_asin':     None,
    },
    {
        'id': 'carman-muesli-bars-classic-6pk',
        'woolworths_term': 'carmans classic fruit  nut bars',
        'coles_term':      'carmans classic fruit  nut bars',
        'amazon_asin':     None,
    },
    {
        'id': 'weetbix-bites-wild-berry-500g',
        'woolworths_term': 'sanitarium weet-bix bites wild berry',
        'coles_term':      'sanitarium weet-bix bites wild berry',
        'amazon_asin':     None,
    },
    {
        'id': 'beef-mince-regular-1kg',
        'woolworths_term': 'ww beef mince 3 star',
        'coles_term':      'ww beef mince 3 star',
        'amazon_asin':     None,
    },
    {
        'id': 'chicken-breast-fillets-1kg',
        'woolworths_term': 'ww chicken breast fillets skinless',
        'coles_term':      'ww chicken breast fillets skinless',
        'amazon_asin':     None,
    },
    {
        'id': 'lamb-shoulder-chops-1kg',
        'woolworths_term': 'ww lamb shoulder chops fresh',
        'coles_term':      'ww lamb shoulder chops fresh',
        'amazon_asin':     None,
    },
    {
        'id': 'pork-loin-chops-1kg',
        'woolworths_term': 'coles pork loin chops boneless',
        'coles_term':      'coles pork loin chops boneless',
        'amazon_asin':     None,
    },
    {
        'id': 'salmon-fillets-skin-on-4pk',
        'woolworths_term': 'tassal salmon fillets skin on',
        'coles_term':      'tassal salmon fillets skin on',
        'amazon_asin':     None,
    },
    {
        'id': 'coles-beef-rump-steak-500g',
        'woolworths_term': 'coles beef rump steak fresh',
        'coles_term':      'coles beef rump steak fresh',
        'amazon_asin':     None,
    },
    {
        'id': 'dondale-bacon-rashers-500g',
        'woolworths_term': 'don bacon short rashers pack',
        'coles_term':      'don bacon short rashers pack',
        'amazon_asin':     None,
    },
    {
        'id': 'primas-frankfurts-skinless-1kg',
        'woolworths_term': 'primo skinless frankfurts tub',
        'coles_term':      'primo skinless frankfurts tub',
        'amazon_asin':     None,
    },
    {
        'id': 'primo-sliced-ham-value-pack',
        'woolworths_term': 'primo english ham sliced value pack',
        'coles_term':      'primo english ham sliced value pack',
        'amazon_asin':     None,
    },
    {
        'id': 'safcol-premium-salmon-100g',
        'woolworths_term': 'safcol salmon in springwater',
        'coles_term':      'safcol salmon in springwater',
        'amazon_asin':     None,
    },
    {
        'id': 'primo-chorizo-sausage-375g',
        'woolworths_term': 'primo chorizo twin pack',
        'coles_term':      'primo chorizo twin pack',
        'amazon_asin':     None,
    },
    {
        'id': 'woolworths-beef-sausages-18pk',
        'woolworths_term': 'ww thin beef sausages value pack',
        'coles_term':      'ww thin beef sausages value pack',
        'amazon_asin':     None,
    },
    {
        'id': 'mccain-frozen-chips-1kg',
        'woolworths_term': 'mccain frozen chips straight cut',
        'coles_term':      'mccain frozen chips straight cut',
        'amazon_asin':     None,
    },
    {
        'id': 'birds-eye-fish-fingers-375g',
        'woolworths_term': 'birds eye fish fingers 15pk',
        'coles_term':      'birds eye fish fingers 15pk',
        'amazon_asin':     None,
    },
    {
        'id': 'mccain-frozen-pizza-bbq-400g',
        'woolworths_term': 'mccain frozen pizza bbq chicken',
        'coles_term':      'mccain frozen pizza bbq chicken',
        'amazon_asin':     None,
    },
    {
        'id': 'nannas-frozen-apple-pie-600g',
        'woolworths_term': 'nannas frozen family apple pie',
        'coles_term':      'nannas frozen family apple pie',
        'amazon_asin':     None,
    },
    {
        'id': 'patties-party-pies-12pk',
        'woolworths_term': 'patties party beef pies 12pk',
        'coles_term':      'patties party beef pies 12pk',
        'amazon_asin':     None,
    },
    {
        'id': 'four-twenty-meat-pies-4pk',
        'woolworths_term': 'four n twenty meat pies pack',
        'coles_term':      'four n twenty meat pies pack',
        'amazon_asin':     None,
    },
    {
        'id': 'diana-chan-pork-dumplings',
        'woolworths_term': 'diana chan pork  chive dumplings',
        'coles_term':      'diana chan pork  chive dumplings',
        'amazon_asin':     None,
    },
    {
        'id': 'steer-frozen-vegetables-peas-1kg',
        'woolworths_term': 'birds eye frozen garden peas',
        'coles_term':      'birds eye frozen garden peas',
        'amazon_asin':     None,
    },
    {
        'id': 'sara-lee-french-vanilla-cheesecake',
        'woolworths_term': 'sara lee french vanilla cheesecake',
        'coles_term':      'sara lee french vanilla cheesecake',
        'amazon_asin':     None,
    },
    {
        'id': 'mccain-frozen-lasagne-400g',
        'woolworths_term': 'mccain frozen lasagne meal',
        'coles_term':      'mccain frozen lasagne meal',
        'amazon_asin':     None,
    },
    {
        'id': 'patties-sausage-rolls-12pk',
        'woolworths_term': 'patties party sausage rolls 12pk',
        'coles_term':      'patties party sausage rolls 12pk',
        'amazon_asin':     None,
    },
    {
        'id': 'steers-garlic-bread-twin-pack',
        'woolworths_term': 'la famiglia garlic bread twin pack',
        'coles_term':      'la famiglia garlic bread twin pack',
        'amazon_asin':     None,
    },
    {
        'id': 'colgate-toothpaste-total-115g',
        'woolworths_term': 'colgate total clean mint toothpaste',
        'coles_term':      'colgate total clean mint toothpaste',
        'amazon_asin':     None,
    },
    {
        'id': 'palmolive-shampoo-milk-honey-350ml',
        'woolworths_term': 'palmolive shampoo milk  honey',
        'coles_term':      'palmolive shampoo milk  honey',
        'amazon_asin':     None,
    },
    {
        'id': 'rexona-men-sport-deodorant-250ml',
        'woolworths_term': 'rexona men sport deodorant aerosol',
        'coles_term':      'rexona men sport deodorant aerosol',
        'amazon_asin':     None,
    },
    {
        'id': 'radox-shower-gel-lemon-500ml',
        'woolworths_term': 'radox shower gel lemon  tea tree',
        'coles_term':      'radox shower gel lemon  tea tree',
        'amazon_asin':     None,
    },
    {
        'id': 'colgate-plax-mouthwash-mint-500ml',
        'woolworths_term': 'colgate plax freshmint mouthwash',
        'coles_term':      'colgate plax freshmint mouthwash',
        'amazon_asin':     None,
    },
    {
        'id': 'head-shoulders-clean-shampoo-400ml',
        'woolworths_term': 'head  shoulders clean shampoo',
        'coles_term':      'head  shoulders clean shampoo',
        'amazon_asin':     None,
    },
    {
        'id': 'pantene-conditioner-smooth-350ml',
        'woolworths_term': 'pantene conditioner daily moisture',
        'coles_term':      'pantene conditioner daily moisture',
        'amazon_asin':     None,
    },
    {
        'id': 'palmolive-soap-bars-milk-honey-4pk',
        'woolworths_term': 'palmolive soap bars moisture care',
        'coles_term':      'palmolive soap bars moisture care',
        'amazon_asin':     None,
    },
    {
        'id': 'dove-body-wash-beauty-cream-1l',
        'woolworths_term': 'dove body wash beauty nourishing',
        'coles_term':      'dove body wash beauty nourishing',
        'amazon_asin':     None,
    },
    {
        'id': 'gillette-mach3-razor-blades-4pk',
        'woolworths_term': 'gillette mach3 razor blades refills',
        'coles_term':      'gillette mach3 razor blades refills',
        'amazon_asin':     None,
    },
    {
        'id': 'lynx-africa-body-spray-155ml',
        'woolworths_term': 'lynx africa men body spray',
        'coles_term':      'lynx africa men body spray',
        'amazon_asin':     None,
    },
    {
        'id': 'listerine-freshburst-mouthwash-250ml',
        'woolworths_term': 'listerine freshburst mouthwash',
        'coles_term':      'listerine freshburst mouthwash',
        'amazon_asin':     None,
    },
    {
        'id': 'huggies-nappies-size-4-60pk',
        'woolworths_term': 'huggies ultra dry nappies size 4',
        'coles_term':      'huggies ultra dry nappies size 4',
        'amazon_asin':     None,
    },
    {
        'id': 'johnsons-baby-wipes-fragrance-free-80pk',
        'woolworths_term': 'johnsons baby wipes fragrance free',
        'coles_term':      'johnsons baby wipes fragrance free',
        'amazon_asin':     None,
    },
    {
        'id': 'baby-love-nappies-size-3-50pk',
        'woolworths_term': 'babylove cosifit nappies size 3',
        'coles_term':      'babylove cosifit nappies size 3',
        'amazon_asin':     None,
    },
    {
        'id': 'curash-baby-wipes-soap-free-80pk',
        'woolworths_term': 'curash baby wipes soap free',
        'coles_term':      'curash baby wipes soap free',
        'amazon_asin':     None,
    },
    {
        'id': 'farex-baby-rice-cereal-125g',
        'woolworths_term': 'farex baby cereal rice',
        'coles_term':      'farex baby cereal rice',
        'amazon_asin':     None,
    },
    {
        'id': 'sudocrem-baby-healing-cream-125g',
        'woolworths_term': 'sudocrem nappy recovery cream',
        'coles_term':      'sudocrem nappy recovery cream',
        'amazon_asin':     None,
    },
    {
        'id': 'karicare-toddler-milk-stage-3-900g',
        'woolworths_term': 'karicare toddler milk stage 3 formula',
        'coles_term':      'karicare toddler milk stage 3 formula',
        'amazon_asin':     None,
    },
    {
        'id': 'bellamys-organic-apple-cinnamon-120g',
        'woolworths_term': 'bellamys organic apple cinnamon puree',
        'coles_term':      'bellamys organic apple cinnamon puree',
        'amazon_asin':     None,
    },
    {
        'id': 'raffertys-garden-banana-pear-120g',
        'woolworths_term': 'raffertys garden custard banana pear',
        'coles_term':      'raffertys garden custard banana pear',
        'amazon_asin':     None,
    },
    {
        'id': 'baby-balm-johnson-100ml',
        'woolworths_term': 'johnsons baby moisturizing balm',
        'coles_term':      'johnsons baby moisturizing balm',
        'amazon_asin':     None,
    },
    {
        'id': 'pedigree-dog-food-beef-12kg-bag',
        'woolworths_term': 'pedigree dry dog food beef bag',
        'coles_term':      'pedigree dry dog food beef bag',
        'amazon_asin':     None,
    },
    {
        'id': 'dine-cat-food-tuna-pouch-85g',
        'woolworths_term': 'dine daily wet cat food tuna',
        'coles_term':      'dine daily wet cat food tuna',
        'amazon_asin':     None,
    },
    {
        'id': 'supercoat-dog-food-chicken-26kg',
        'woolworths_term': 'purina supercoat adult dry dog food',
        'coles_term':      'purina supercoat adult dry dog food',
        'amazon_asin':     None,
    },
    {
        'id': 'optimum-dry-cat-food-chicken-800g',
        'woolworths_term': 'optimum adult dry cat food chicken',
        'coles_term':      'optimum adult dry cat food chicken',
        'amazon_asin':     None,
    },
    {
        'id': 'my-dog-beef-poultry-meat-400g',
        'woolworths_term': 'my dog wet dog food beef cans',
        'coles_term':      'my dog wet dog food beef cans',
        'amazon_asin':     None,
    },
    {
        'id': 'whiskas-cat-food-poultry-12pk',
        'woolworths_term': 'whiskas wet cat food gravy pouches',
        'coles_term':      'whiskas wet cat food gravy pouches',
        'amazon_asin':     None,
    },
    {
        'id': 'schmackos-dog-treats-beef-strap',
        'woolworths_term': 'schmackos strapz dog treats beef',
        'coles_term':      'schmackos strapz dog treats beef',
        'amazon_asin':     None,
    },
    {
        'id': 'fancies-cat-treat-puree-4pk',
        'woolworths_term': 'fancy feast puree kiss treats',
        'coles_term':      'fancy feast puree kiss treats',
        'amazon_asin':     None,
    },
    {
        'id': 'tux-dog-biscuits-value-pack-1kg',
        'woolworths_term': 'purina lucky dog bones biscuits',
        'coles_term':      'purina lucky dog bones biscuits',
        'amazon_asin':     None,
    },
    {
        'id': 'friskies-cat-dry-food-15kg-box',
        'woolworths_term': 'purina friskies seafood sensations',
        'coles_term':      'purina friskies seafood sensations',
        'amazon_asin':     None,
    }
]
